### ISSUE TITLE
Crash in 1.6.2 when taking Fabrishot screenshot

### ISSUE THREAD

**Issue by manuelgrabowski** [ramidzkh/fabrishot#28]
Hey there,

after updating to 1.6.2 I'm getting a reproducible crash when trying to take a screenshot using the mod. I've verified that it works in 1.6.0 with nothing else about my installation different other than the mod version. I also tried setting the newly introduced delay feature to 0 in order to get as close to the old behavior as possible, but the minimum is 3, so it seems I can't "disable" this new feature (although I'm kinda assuming that 3 was just the old default value anyway and has not much to do with the crash).

Here's my crash-log, let me know if you need anything else.

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/6/22, 7:08 PM
Description: Unexpected error

java.lang.IllegalAccessError: class link.infra.screenshotclipboard.FabrishotCompat tried to access private field me.ramidzkh.fabrishot.capture.Dimension.width (link.infra.screenshotclipboard.FabrishotCompat and me.ramidzkh.fabrishot.capture.Dimension are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @45ac5f9b)
	at link.infra.screenshotclipboard.FabrishotCompat.lambda$init$0(FabrishotCompat.java:9)
	at me.ramidzkh.fabrishot.event.FramebufferCaptureCallback.lambda$static$0(FramebufferCaptureCallback.java:40)
	at me.ramidzkh.fabrishot.capture.FramebufferCapturer.capture(FramebufferCapturer.java:81)
	at me.ramidzkh.fabrishot.capture.CaptureTask.onRenderTick(CaptureTask.java:65)
	at me.ramidzkh.fabrishot.Fabrishot.onRenderPreOrPost(Fabrishot.java:79)
	at net.minecraft.class_310.handler$cba000$postRender(class_310.java:9000)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at link.infra.screenshotclipboard.FabrishotCompat.lambda$init$0(FabrishotCompat.java:9)
	at me.ramidzkh.fabrishot.event.FramebufferCaptureCallback.lambda$static$0(FramebufferCaptureCallback.java:40)
	at me.ramidzkh.fabrishot.capture.FramebufferCapturer.capture(FramebufferCapturer.java:81)
	at me.ramidzkh.fabrishot.capture.CaptureTask.onRenderTick(CaptureTask.java:65)
	at me.ramidzkh.fabrishot.Fabrishot.onRenderPreOrPost(Fabrishot.java:79)

-- Affected level --
Details:
	All players: 1 total; [class_746['manu__faktur'/2183382, l='ClientLevel', x=-5.87, y=128.00, z=-120.21]]
	Chunk stats: 16384, 3653
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,223,0), Section: (at 0,15,0 in 0,13,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 104620316 game time, 107926596 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, VanillaTweaks_r812586.zip, continuity/default, continuity/glass_pane_culling_fix, firework-rocket-variants-e2050.zip, ore-locator-1-17.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 889411432 bytes (848 MiB) / 2147483648 bytes (2048 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1165
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36785.00
	Virtual memory used (MB): 22791.67
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 748.31
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx12288m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.18-fabric0.43.1-1.3
		antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
		authme: Auth Me 2.2.0
		autoreconnect: AutoReconnect 1.3.2
		betterchristmaschests: Better Christmas Chests 3.0.0
		blue_endless_jankson: jankson 1.2.1
		bowinfinityfix: Bow Infinity Fix rv11
		carpet: Carpet Mod 1.4.56
		carpet-extra: Carpet Extra 1.4.56
		carpet-fixes: Carpet Fixes 1.18.1-1.5.1+v220107
		citresewn: CITResewn 0.8.1-1.18
		clear-skies: Clear Skies 2.0.88
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		continuity: Continuity 1.0.3+1.18
		controlling: Controlling For Fabric 9.0+14
		crowdin-translate: CrowdinTranslate 1.4+1.18
		custom-fog: Custom Fog 2.1.0
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.12.12
		fabrishot: Fabrishot 1.6.2
		ftc: Fabric Title Changer 1.0.6
		indium: Indium 1.0.2-alpha1+mc1.18
		inspecio: Inspecio 1.2.1+1.18
		inventoryprofilesnext: Inventory Profiles Next 1.3.0
		itemscroller: Item Scroller 0.15.0
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		keepheadnames: Keep Head Names 1.5.1
		keybinds_plus: Keybinds Plus 1.1.0-1.18.1
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		litematica: Litematica 0.10.1
		lithium: Lithium 0.7.7
		malilib: MaLiLib 0.11.6
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.17
		minecraft: Minecraft 1.18.1
		minihud: MiniHUD 0.21.3
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		namepain: Name Pain 1.4.0
		noexpensive: NoExpensive 1.18-Fabric-1.2.0
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		phosphor: Phosphor 0.8.1
		pride: Pride Lib 1.1.0+1.17
		replaymod: Replay Mod 1.18.1-2.6.3
		screenshotclipboard: Screenshot to Clipboard 1.0.7
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		simple-rpc: Simple Rpc 2.7.1
		sodium: Sodium 0.4.0-alpha6+build.14
		spruceui: SpruceUI 3.3.0+1.17
		stendhal: Stendhal 1.2.0-1.18
		tweakeroo: Tweakeroo 0.12.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.65, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, Fabric Mods, file/VanillaTweaks_r812586.zip, continuity/default, continuity/glass_pane_culling_fix, file/firework-rocket-variants-e2050.zip (incompatible), file/ore-locator-1-17.zip (incompatible)
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 3900X 12-Core Processor 
```

**Comment by ramidzkh** [comment]
Ah I made a breaking change, didn't remember can mods use Fabrishot as api 😅

Probably would be easiest for @comp500 to fix himself

**Comment by manuelgrabowski** [comment]
Ahh, I was wondering if copying the Fabrishot screenshots to the clipboard worked "accidentally", but it makes sense that some extra work was done in that mod. I'll create an issue over there, thanks for the hint! :)
