### ISSUE TITLE
Modrinth version?

### ISSUE THREAD

**Issue by axium1998** [ramidzkh/fabrishot#81]
While updating my 1.20.4 modrinth profile today, fabrishot automatically updated to version 1.13.0, which gives the following error:

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabrishot' (fabrishot) 1.13.0 with any version that is compatible with:
		 - minecraft 1.20.4
More details:
	 - Mod 'Fabrishot' (fabrishot) 1.13.0 requires version 1.20.5 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Looks like the mod is built against minecraft 1.20.5, but was uploaded to modrinth with minecraft version 1.20.4
Manually changing fabrishot's version back to 1.12.1 allows the game to load, so it's not a major issue, just ever so slightly annoying ;)

**Comment by ramidzkh** [comment]
Oh it looks like they update forgot to update that... fixed now
